### ISSUE TITLE
How to Hide pop-out

### ISSUE THREAD

**Issue by harshasaha** [Marcelh1983/angular-document-viewer#21]
![image](https://user-images.githubusercontent.com/33347915/71976874-69582680-323d-11ea-9856-9141437c2f01.png)

**Comment by Marcelh1983** [comment]
Hi @harshasaha ,

Really hiding this button is not possible. the google viewer is loaded in an iframe, and because its on a different domain it's not possible to modify html elements in the iframe.

But I did create a new version 1.27 which allows you set a new property called: disableContent. when you set this option to: 'popout' it will still show the button for a few seconds but its not clickable, because of an overlay it renders. If you set the value tot 'popout-hide' it renders a white overlay which makes the button invisible, but you will see a white block while loading.

Please let me know if this solves your problem

**Comment by harshasaha** [comment]
@Marcelh1983 Thank you for the quick reply.

It's working as the condition as you mentioned.

Please let me know if you find any other solution.

**Comment by Marcelh1983** [comment]
Hi @harshasaha `npm i ngx-doc-viewer@next` will have the mammoth viewer. Which converts docx to html locally. It will give you all the possibilities to style the previewer as you want.

But the previewer has limitations, so can imagine it's not usefull for all projects,

Also add mammoth: 
```sh
npm install mammoth --save
```
and make sure mammoth.browser.min.js is loaded. For the angular/cli you would add the following in angular.json:

```json
    "scripts": [
        "node_modules/mammoth/mammoth.browser.min.js"
    ]
```
See the demo site in local-files branch for example code.
