### ISSUE TITLE
Office - option to remove Menu and required Sub Menu items 

### ISSUE THREAD

**Issue by leelaakula** [Marcelh1983/angular-document-viewer#23]
Hi Marcel,

Can we hide or remove Menu button from the bottom toolbar in Office Viewer.

Add or Remove Sub Menus items as a feature 

Thanks
Anuroop
![office viewer](https://user-images.githubusercontent.com/38076999/72133016-72183c00-33a6-11ea-84b2-a1ecd3e94bf1.JPG)

**Comment by Marcelh1983** [comment]
Hi @leelaakula because the library loads the office viewer in an iframe, there is no way to configure/modify anything from the office viewer. The only thing you could do is render an absolute div on top of the menu so its not visible/accessible. I did the same thing for the google viewer yesterday, see commits. I can do the same for the office viewer, but first I'm working on something else. Feel free to add it yourself and create a pull request and let me know if you start :) otherwise I'll add it within a few days.

**Comment by Marcelh1983** [comment]
you can use option: disableContent: popout-hide'
