### ISSUE TITLE
In Office Docx Type - PDF theme coming up

### ISSUE THREAD

**Issue by leelaakula** [Marcelh1983/angular-document-viewer#29]
Hi @Marcelh1983 

When using office viewer, for .docx file type 

We can see that file-view is taken and shown as PDF. 

We are seeing **_document.pdf_** as file name
![image](https://user-images.githubusercontent.com/38076999/72686584-59352680-3b1c-11ea-8eb1-cf002dc86a5c.png)

Is this office viewer default behaviour for .docx file format?

Thanks in advance
Anuroop

**Comment by Marcelh1983** [comment]
Hi Anuroop. 
Looks like something goes wrong there. It still shows the pdf file. When using docx format it doesnt show a filename. I'll check what could be the problem in the screenshot

**Comment by leelaakula** [comment]
Hi @Marcelh1983 

I Think I got the issue, We are having Accessibility Mode in menu options, If it is selected then whenever office viewer loads, it is starting in this mode. Because of that we are having that above PDF issue.

Will be there an option to reset **Accessibility Mode** option whenever we load viewer?

Thanks 
Anuroop

**Comment by TaruniSurampally** [comment]
Will ngx-doc-viewer not support Presentation files with .pptx format.
I tried to use a .ppt extension it works , but when i try to use .pptx extn it does not preview the doc, and it is directly opening the doc in the powerpoint app.
For PDF files, it is directly downloading the PDF without giving the preview (preview is blank).

Thanks in advance

**Comment by TaruniSurampally** [comment]
disableContent: 'none' | 'all' | 'popout' | 'popout-hide' = 'none':
none: no overlay
all: adds an overlay to the whole iframe, which makes nothing in the document clickable/selectable
popout: adds an overlay over googles popout button or office popout and menu which disables just this button/menu but keeps giving the possibility to select text. The popout button is still visible (for google during a few seconds) but not clickable.
popout-hide: see popup, **instead of an transparent overlay a white one**. 

When i use the above property on my html tempate, when showing the preview , there is a white patch coming in the place of the disabled content (**instead of an transparent overlay a white one.**).
Is there any way we can remove this white patch as it looks odd.

**Comment by Marcelh1983** [comment]
Hi @TaruniSurampally  I cannot remove the white path. Maybe you do a hack like: try to hide the iframe for a second.
