### ISSUE TITLE
Reporting service, office mode - xlsx, docx not work

### ISSUE THREAD

**Issue by b-mi** [Marcelh1983/angular-document-viewer#35]
Viewer does not show xlsx, docx export form Sql Server reporting service, in office mode.

Valid link which download valid xlsx file, for example  'http://srv2016.root.page.com/ReportServer/Pages/ReportViewer.aspx?/NNWAP/crm_master_status_report&rs:Format=EXCELOPENXML' ends with error in viewer in office mode with error 'No page found at https://www.office.com/redir.aspx?assetid=HA102724036'. 

How to view docx, xlsx from SSRS?

**Comment by Marcelh1983** [comment]
Hi @b-mi , http://srv2016.root.page.com is not publicly available, therefor the office viewer cannot render the document

**Comment by b-mi** [comment]
No, real link I use is publicly available, as I wrote - that link work in browser and correctly download  document. Link above is for example - it does not work. 

Does angular-document-viewer correctly work with exports from SSRS - in common - have anybody such experience?

**Comment by Marcelh1983** [comment]
Ok, could be the the viewer cannot determine the right mime type. I experienced something like that viewing documents from azure blob storage that where automatically classified as 'application/octet-stream' instead of 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' after explicitly setting the right mime type it worked. The google viewer could handle the file without the right mime type. Did you try the google viewer?

**Comment by b-mi** [comment]
Yes, I use Chrome.  I will try look at mime type. Thx for now.

**Comment by Marcelh1983** [comment]
I mean, did you try to use the google-viewer: mode="google" to see if the document load there?

**Comment by b-mi** [comment]
Yes I tried mode="google" too, it did not show document too.
