### ISSUE TITLE
Google Viewer doesn't always load file

### ISSUE THREAD

**Issue by avoThomas** [Marcelh1983/angular-document-viewer#45]
When using the Google viewer to try and load a file, it doesn't always render the file first time or after a few tries. 
Whats confusing is that the loaded event is emitted from the doc viewer even though I still can't see the document. 

The viewer has been implemented as follows:
```
<ngx-doc-viewer
  id="doc-viewer"
  *ngIf="doc | async"
  url="{{resumeURL}}"
  viewer="google"
  class="doc-viewer"
  (loaded)="resumeLoaded()"
  [hidden]="loadingSubject | async"
  [queryParams]="getLanguage()"
  googleCheckContentLoaded="true">
</ngx-doc-viewer>
```
And then the following is output to my console: 
The top iframe is when it loads correctly and the bottom iframe is when it doesn't load correctly.
![consoleoutput](https://user-images.githubusercontent.com/51990494/80359473-29658f80-887e-11ea-8944-329f98360e1f.png)

We would use the office viewer as we want to display docx/doc files, but that has a cookies banner at the top.

**Comment by kaleu50** [comment]
+1

**Comment by Marcelh1983** [comment]
Hi @avoThomas ,

The google viewer has some issues with first time loading. I don't exactly know why and whats the real problem.
I implemented the reload function because of [this](https://stackoverflow.com/questions/40414039/google-docs-viewer-returning-204-responses-no-longer-working-alternatives) and made this work-around configurable by be able to disable this reloading and configuring your own interval.

Could you clone this repository and set your document url in demo application. Maybe you'll find the problem and make a PR 😄.
If you have an example of a document that has this problem, you can send me the url and I can do some tests in the weekend as well.

**Comment by Marcelh1983** [comment]
Hi @avoThomas, @kaleu50 I tried several documents on the internet to try to reproduce your problem. I couldn't reproduce. Is there a way I can test with the document you are using? Or do you have Stackblitz or something were I can reproduce the problem?
